t = int(input("Введите значение t: "))
v = int(input("Введите значение v: "))
x = int(input("Введите значение x: "))
y = int(input("Введите значение y: "))
print("а)")
print("5", 10)
print("\nб)")
print("100", t)
print("\nв)")
print(x, "25")
print("\n7 см 1949", v, x, y)
print("\nПримечание")
print("t, v, x и y - переменные величины целого типа")