a = int(input("Введите значение t: "))
b = int(input("Введите значение v: "))
x = int(input("Введите значение x: "))
y = int(input("Введите значение y: "))
print("а)")
print("2 кг", )
print("\nб)")
print("1", a)
print("\nв)")
print(x, "y")
print("\n13 17  19", b, 5, y)
print("\nПримечание")
print("a, b, x и y - переменные величины целого типа")